name: 'Extra blb config'
description: "Adds mt bootstrap layout builder."
type: 'Site'
install:
  - bootstrap_layout_builder
  - layout_builder_blocks
  - layout_builder_modal
  - layout_builder_restrictions
  - mt_layout_builder
  - baseplus
config:
  strict:
    - core.entity_form_display.node.mt_landing_page.default
    - core.entity_view_display.node.mt_landing_page.default
    - core.entity_view_display.node.mt_landing_page.teaser
    - field.field.node.mt_landing_page.layout_builder__layout
    - field.storage.node.layout_builder__layout
    - node.type.mt_landing_page
