name: 'Mt extra blb config'
description: "Adds mt layout builder."
type: 'Site'
install:
  - bootstrap_layout_builder
  - layout_builder_blocks
  - layout_builder_modal
  - layout_builder_restrictions
  - mt_layout_builder
config:
  strict: false